services:
  rabbitmq:
    image: bitnami/rabbitmq:3.8
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment: 
      - RABBITMQ_USERNAME=mq
      - RABBITMQ_PASSWORD=mq
