services:
    vault:
        image: hashicorp/vault:1.8.2
        restart: always
        # volumes:
        #   - /vault/data
        #   - /etc/vault/logs
        ports:
          - "8200:8200"
        environment:
          VAULT_DEV_ROOT_TOKEN_ID: 'root'
          VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
        cap_add:
          - IPC_LOCK
        container_name: vault_dev
        entrypoint: "vault server -dev"
        # if you want to use v1 kv engine
        # entrypoint: "vault server -dev-kv-v1"
    
  