version: '3.8'
services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql_data:/bitnami/postgresql
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
